"""edit exercise in session keys

Revision ID: 3b199b1df6b5
Revises: 5ec4e70ce2fb
Create Date: 2024-08-05 20:32:16.729144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b199b1df6b5'
down_revision: Union[str, None] = '5ec4e70ce2fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
