"""edit exercise in session

Revision ID: 5ec4e70ce2fb
Revises: cd1f62096047
Create Date: 2024-08-05 20:27:21.340083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ec4e70ce2fb'
down_revision: Union[str, None] = 'cd1f62096047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises_in_sessions', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('exercises_in_sessions', sa.Column('sets_number', sa.Integer(), nullable=False))
    op.add_column('exercises_in_sessions', sa.Column('reps_number', sa.Integer(), nullable=False))
    op.add_column('exercises_in_sessions', sa.Column('weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises_in_sessions', 'weight')
    op.drop_column('exercises_in_sessions', 'reps_number')
    op.drop_column('exercises_in_sessions', 'sets_number')
    op.drop_column('exercises_in_sessions', 'id')
    # ### end Alembic commands ###
